{% set name = "userpath" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61f84899b7280800a8b6cc1b959a0cf250f6757e6f6c7176d7455bb693a4423a

build:
  number: 0
  noarch: python
  entry_points:
    - userpath = userpath.cli:userpath
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - python >=3.6

test:
  imports:
    - userpath
    - pip
  commands:
    - userpath --help
    - pip check

about:
  home: https://github.com/ofek/userpath
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Cross-platform tool for adding locations to the user PATH, no elevated privileges required!
  dev_url: https://github.com/ofek/userpath

extra:
  recipe-maintainers:
    - mariusvniekerk
